
---
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: admissionregistration.k8s.io/v1
{{- else -}}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ include "actions-runner-controller.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "actions-runner-controller.servingCertName" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "actions-runner-controller.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-actions-summerwind-dev-v1alpha1-runner
  failurePolicy: Fail
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
  sideEffects: None                                                                                                                                                                    ││                                                                                                                                                                                  │
  admissionReviewVersions: ["v1beta1"]
  {{- end }}
  name: mutate.runner.actions.summerwind.dev
  rules:
  - apiGroups:
    - actions.summerwind.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runners
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "actions-runner-controller.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-actions-summerwind-dev-v1alpha1-runnerdeployment
  failurePolicy: Fail
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
  sideEffects: None                                                                                                                                                                    ││                                                                                                                                                                                  │
  admissionReviewVersions: ["v1beta1"]
  {{- end }}
  name: mutate.runnerdeployment.actions.summerwind.dev
  rules:
  - apiGroups:
    - actions.summerwind.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnerdeployments
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "actions-runner-controller.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-actions-summerwind-dev-v1alpha1-runnerreplicaset
  failurePolicy: Fail
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
  sideEffects: None                                                                                                                                                                    ││                                                                                                                                                                                  │
  admissionReviewVersions: ["v1beta1"]
  {{- end }}
  name: mutate.runnerreplicaset.actions.summerwind.dev
  rules:
  - apiGroups:
    - actions.summerwind.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnerreplicasets

---
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: admissionregistration.k8s.io/v1
{{- else -}}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ include "actions-runner-controller.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "actions-runner-controller.servingCertName" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "actions-runner-controller.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-actions-summerwind-dev-v1alpha1-runner
  failurePolicy: Fail
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
  sideEffects: None                                                                                                                                                                    ││                                                                                                                                                                                  │
  admissionReviewVersions: ["v1beta1"]
  {{- end }}
  name: validate.runner.actions.summerwind.dev
  rules:
  - apiGroups:
    - actions.summerwind.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runners
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "actions-runner-controller.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-actions-summerwind-dev-v1alpha1-runnerdeployment
  failurePolicy: Fail
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
  sideEffects: None                                                                                                                                                                    ││                                                                                                                                                                                  │
  admissionReviewVersions: ["v1beta1"]
  {{- end }}
  name: validate.runnerdeployment.actions.summerwind.dev
  rules:
  - apiGroups:
    - actions.summerwind.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnerdeployments
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "actions-runner-controller.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-actions-summerwind-dev-v1alpha1-runnerreplicaset
  failurePolicy: Fail
  {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
  sideEffects: None                                                                                                                                                                    ││                                                                                                                                                                                  │
  admissionReviewVersions: ["v1beta1"]
  {{- end }}
  name: validate.runnerreplicaset.actions.summerwind.dev
  rules:
  - apiGroups:
    - actions.summerwind.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnerreplicasets
